### ISSUE TITLE
Rust -> Substrate implementation

### ISSUE THREAD

**Issue by justinfrevert** [drewstone/truecoin#11]
It'd be cool if there was a Substrate implementation of this. Not sure of the feasibility.

Selfishly, for my own learning, I'd love to adapt to Rust. Then look into whether it'd be possible to implement in Substrate through an OCW or something(mainly thinking about whether the complexity might be too much for a pallet).

**Comment by drewstone** [comment]
I think it would actually be much easier to build this in rust than it was in Solidity.
